services:
  db:
    profiles: [ "db", "all" ]
    image: cockroachdb/cockroach:latest-v24.3
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach_data:/cockroach/cockroach-data

  backend:
    profiles: [ "api", "all" ]
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:${PORT}"
    volumes:
      - ./backend:/api


  frontend:
    profiles: [ "front", "all" ]
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  cockroach_data:
